### ISSUE TITLE
check mapping is provided in internal_attributes at device provision

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/sigfox-iotagent#22]
A special internal attribute called mapping must be provided, containing the structure of the data attribute of the device.
```
  "internal_attributes": [
    {
      "mapping": "theCounter::uint:32  theParam1::uint:32 param2::uint:8 tempDegreesCelsius::uint:8  voltage::uint:16"
    }
```
Currently no check is performed

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/sigfox-iotagent/pull/23
