### ISSUE TITLE
Device not found in Update

### ISSUE THREAD

**Issue by carloscorrales** [telefonicaid/sigfox-iotagent#57]
I'm having problems with updating a device data using the Sigfox IoT Agent. After creating the device, I'm able to retrieve it using the admin API:

```
curl -H "fiware-service: dumbMordor" -H "fiware-servicepath: /deserts" "sigfox-agent:4041/iot/devices"
{"count":1,"devices":[{"device_id":"sigApp2","service":"dumbMordor","service_path":"/deserts","entity_name":"sigApp2","entity_type":"SIGFOX","attributes":[{"object_id":"time","name":"time","type":"String"},{"object_id":"statin","name":"statin","type":"String"},{"object_id":"lng","name":"lng","type":"String"},{"object_id":"lat","name":"lat","type":"String"},{"object_id":"theCounter","name":"theCounter","type":"Integer"},{"object_id":"theParam1","name":"theParam1","type":"Integer"},{"object_id":"param2","name":"param2","type":"Integer"},{"object_id":"tempDegreesCelsius","name":"tempDegreesCelsius","type":"Integer"},{"object_id":"voltage","name":"voltage","type":"Integer"}],"lazy":[],"commands":[],"static_attributes":[],"internal_attributes":[{"mapping":"theCounter::uint:32  theParam1::uint:32 param2::uint:8 tempDegreesCelsius::uint:8  voltage::uint:16"}],"protocol":"SIGFOX"}]}
```

As you can see, there is a device with id sigApp2 and different parameters, using that service and service-path.

However, when I try to update the device data using the southbound API, it says that the device doesn't exist:

```
curl -H "fiware-service: dumbMordor" -H "fiware-servicepath: /deserts" "sigfox-agent:17428/update?id=sigApp2&time=1430908992&statin=0817&lng=-4&lat=41&data=000000020000000000230c6f"

{"name":"DEVICE_NOT_FOUND","message":"No device was found with id:sigApp2","code":404}
```

I tried also adding the API Key, k=TEF (which is the default one), with no results.

Could you please help me?

**Comment by fgalan** [comment]
Maybe the logs can provide some additional info. Which log trace is printed when you send the update curl?

**Comment by carloscorrales** [comment]
Hi Fermín,

We were able somehow to make it work (but it is not the proper solution). It seems that the Southbound is not using the fiware-service and fiware-servicepath headers, but it uses the value that is stored in the config.js file. The default value was howtoService, so we modified it to dumbMordor in the config file and it works. However, we think it is not a good solution (even if it works for the current project) because there could be different devices with different fiware-service and they won't work in other scenarios.

**Comment by fgalan** [comment]
Typically, devices use and APIkey in the southbound interface to send measures to IOTA, then IOTA translates it into fiware-service and fiware-servicepath to update the corresponding entities in the IOTA. In other words, devices don't knows about services or service paths: is the IOTA which provides the mapping (based in the provision operations done for these devices or device groups).

However, the above is based on my experience with ITOA-UL and IOTA-JSON. Not fully sure if Sigfox agent works in the same way (although under my understanding it should do).

**Comment by carloscorrales** [comment]
Does this mean that we need to have one IOTA per fiware-service and service-path? I understand your point, but this could also lead to some modifications in the way I thought the IOTAs worked. What would be the recommended way to do it?

**Comment by fgalan** [comment]
> Does this mean that we need to have one IOTA per fiware-service and service-path? 

No, not really.

IOTAs support multitenancy, so the same IOTA instance is able to cope with devices in different services and service paths. The process is roughly as follows:

1. You do a provision request at IOTA using the provisioning API. You can proision groups of devices or individual devices in a given service and service path. In this step you set the API key for the given device/group. You can do as many provision operations as you can, each one potentially in a different service and service path, as long as API keys are different.
2. Your devices send measurements using a given API key. The IOTA checks the API key and knows to which service and subservice is associated. The IOTA progresses an entity update at CB using such service and service path.

At least this is the way it works for IOTA-UL and IOTA-JSON. For details of the provision operations, please check [IOTA Node Lib documentation](https://github.com/telefonicaid/iotagent-node-lib) (provisioning API is common functionality to all IOTAs in the northbound interface, so it is documented in the common library). [This reference](https://thinking-cities.readthedocs.io/en/master/device_api/index.html) may be also useful.

**Comment by carloscorrales** [comment]
Ok Fermín, thanks for the information, I will close the issue in this case.

Best regards
