### ISSUE TITLE
Create RPM and service for the Agent

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/sigfox-iotagent#6]
Create the RPM generation script and add the needed services and configuration files for the IOTA to work as a standard Linux service.

**Comment by fgalan** [comment]
Partly addressed by PR https://github.com/telefonicaid/sigfox-iotagent/pull/32

**Comment by fgalan** [comment]
Partly addressed by PR https://github.com/telefonicaid/sigfox-iotagent/pull/33

**Comment by AlvaroVega** [comment]
This issue should be close, shouldn't be @galan?

**Comment by fgalan** [comment]
My previous comments saying "partially" make me think if something is yet pending... Maybe we should check with @cesarjorgemartinez

**Comment by galan** [comment]
> This issue should be close, shouldn't be @galan?
Huh? You probably where talking to someone else..

**Comment by fgalan** [comment]
Yes... it was due to a missing 'f' (rigth one was @fgalan).

Sorry to disturb you :)

**Comment by fgalan** [comment]
> My previous comments saying "partially" make me think if something is yet pending... Maybe we should check with @cesarjorgemartinez

Discussed at skype. It can be closed.
