### ISSUE TITLE
IoT Agent Manager Connection Refused

### ISSUE THREAD

**Issue by dalxds** [telefonicaid/sigfox-iotagent#98]
I used the docker-compose file on the README with the default configuration.
When starting the container, I get the following error message about the IoT Agent Manager:

```
fiware-iot-agent | time=2021-01-21T11:23:36.285Z | lvl=DEBUG | corr=39e89227-bc1e-4293-a231-a9f70dd26bde | trans=39e89227-bc1e-4293-a231-a9f70dd26bde | op=IoTAgentNGSI.IOTAMService | srv=n/a | subsrv=n/a | msg=Sending registration to the IOTAM:
fiware-iot-agent | {
fiware-iot-agent |     "url": "http://localhost:18082/iot/protocols",
fiware-iot-agent |     "method": "POST",
fiware-iot-agent |     "json": {
fiware-iot-agent |         "protocol": "IoTA-Sigfox",
fiware-iot-agent |         "description": "Sigfox_IoT_Agent_Node",
fiware-iot-agent |         "iotagent": "http://iot-agent:4041",
fiware-iot-agent |         "resource": "/iot/sigfox",
fiware-iot-agent |         "services": []
fiware-iot-agent |     }
fiware-iot-agent | }
fiware-iot-agent |
fiware-iot-agent |  | comp=IoTAgent
fiware-iot-agent | time=2021-01-21T11:23:36.293Z | lvl=ERROR | corr=39e89227-bc1e-4293-a231-a9f70dd26bde | trans=39e89227-bc1e-4293-a231-a9f70dd26bde | op=IoTAgentNGSI.IOTAMService | srv=n/a | subsrv=n/a | msg=Error connecting to IoT Manager: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18082} | comp=IoTAgent
fiware-iot-agent | time=2021-01-21T11:23:36.294Z | lvl=ERROR | corr=39e89227-bc1e-4293-a231-a9f70dd26bde | trans=39e89227-bc1e-4293-a231-a9f70dd26bde | op=IoTAgentNGSI.Alarms | srv=n/a | subsrv=n/a | msg=Raising [IOTAM-ALARM]: "Unknown error connecting with the IoTAM" | comp=IoTAgent
fiware-iot-agent | time=2021-01-21T11:23:36.294Z | lvl=ERROR | corr=39e89227-bc1e-4293-a231-a9f70dd26bde | trans=39e89227-bc1e-4293-a231-a9f70dd26bde | op=IoTAgentSIGFOX.Executable | srv=n/a | subsrv=n/a | msg=Error starting Sigfox IoT Agent: [{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":18082}] Exiting process | comp=IoTAgent
```

I guess the error is about not finding the IoT Agent Manager? 
Is the IoT Agent Manager included in the Sigfox IoT Agent or should it be added in the Docker-Compose separately?

**Comment by fgalan** [comment]
Not sure, but I think that by configuration you can disable the connection attemp to IOTA Manager. At least for the IOTA-UL and IOTA-JSON agents.

**Comment by dalxds** [comment]
Ok. I'll try it, thanks.
If I want to use the IoTA Manager should I add it to the docker-compose file or is it included in the Sigfox Agent?

**Comment by fgalan** [comment]
> If I want to use the IoTA Manager should I add it to the docker-compose file or is it included in the Sigfox Agent?

I think so

**Comment by dalxds** [comment]
In the default Sigfox IoT Agent _config.js_ file there is [this](https://github.com/telefonicaid/sigfox-iotagent/blob/51be93ffb0b25b2560410244bd503d5d272032bb/config.js#L141) object that "tells" the Sigfox IoT Agent to try and connect to the IoT Agent Manager. 
In order for the Sigfox IoT Agent to not try to connect to the IoTA Manager, there shouldn't be any parameters in _config.js_ file as I understand from [here](https://github.com/telefonicaid/iotagent-node-lib/blob/5f4a49bb9392f6bf2a4f3f3c8b68227b5fbafc3c/lib/commonConfig.js#L343).

If someone tries to use the Docker-Compose file provided [here](https://github.com/telefonicaid/iotagent-manager/blob/master/docker/README.md) it doesn't work, since it tries to find the IoT Agent Manager and the IoT Agent Manager doesn't exist in the docker image. Therefore, shouldn't it be preferable for those lines to be commented out in the default _config.js_ or that somehow a parameter is passed in the docker-compose file to either work with or without the IoT Agent Manager.

**Comment by fgalan** [comment]
> 
> 
> In the default Sigfox IoT Agent _config.js_ file there is [this](https://github.com/telefonicaid/sigfox-iotagent/blob/51be93ffb0b25b2560410244bd503d5d272032bb/config.js#L141) object that "tells" the Sigfox IoT Agent to try and connect to the IoT Agent Manager.
> In order for the Sigfox IoT Agent to not try to connect to the IoTA Manager, there shouldn't be any parameters in _config.js_ file as I understand from [here](https://github.com/telefonicaid/iotagent-node-lib/blob/5f4a49bb9392f6bf2a4f3f3c8b68227b5fbafc3c/lib/commonConfig.js#L343).
> 
> If someone tries to use the Docker-Compose file provided [here](https://github.com/telefonicaid/iotagent-manager/blob/master/docker/README.md) it doesn't work, since it tries to find the IoT Agent Manager and the IoT Agent Manager doesn't exist in the docker image.
> Therefore, shouldn't it be preferable for those lines to be commented out in the default _config.js_ or that somehow a parameter is passed in the docker-compose file to either work with or without the IoT Agent Manager.

What you say makes sense...

However, before modifying anything in the repo maybe it's a good idea to see how this is done in other IOTAs (in particular, IOTA-JSON and IOTA-UL). Could you have a look and tell us, please?

**Comment by dalxds** [comment]
In this repo, it was first commented out and then changed to uncommented on [this](https://github.com/telefonicaid/sigfox-iotagent/commit/333f0ec4f70077d28ba22fbe348a92b6bffa4680) commit.

In the IOTA-JSON, there isn't any reference on the IoT Agent Manager in the config.js file.
In the IOTA-UL, the IoT Agent Manager configuration in the config.js file is commented out. ([link](https://github.com/telefonicaid/iotagent-ul/blob/d77f14ec6be45e23e18f79e5826d3fdd39dcddcc/config.js#L242))

**Comment by fgalan** [comment]
Thus, it seems to be a good idea to comment out the section, as in IOTA-UL case.

Could you do it in a pull request, please? Thanks!
